third_project/contact/urls.py
from django.urls import path
from contact import views

app_name='contact'

urlpatterns=[path('',views.contact,name='contact')]

third_project/form/urls.py
from django.urls import path
from form import views

app_name='form'

urlpatterns = [path('',views.form_name_view,name="form"),]

third_project/form2/urls.py
from django.urls import path
from form2 import views

app_name='form2'

urlpatterns=[
    path('',views.form_name_view,name="form2"),
]

third_project/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns=[path('',views.register,name='registration')]

third_project/special/urls.py
from django.urls import path
from . import views

app_name = 'special'

urlpatterns=[path('',views.special,name='special')]

third_project/third_project/urls.py
from django.contrib import admin
from django.urls import path
from index import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('contact/',include('contact.urls')),
    path('form/',include('form.urls')),
    path('form2/',include('form2.urls')),
    path('registration/',include('registration.urls')),
    path('user_login/',include('user_login.urls')),
    path('logout/',include('user_logout.urls')),
    path('special/',include('special.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

third_project/user_login/urls.py
from django.urls import path
from . import views

app_name = 'user_login'

urlpatterns=[path('',views.user_login,name='user_login')]

third_project/user_logout/urls.py
from django.urls import path
from . import views

app_name = 'user_logout'

urlpatterns=[path('',views.user_logout,name='user_logout')]

third_project/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=264)
    last_name = models.CharField(max_length=264)
    email=models.EmailField(max_length=264,unique=True)

    def __str__(self):
        return self.last_name

third_project/form/models.py
from django.db import models

# Create your models here.

third_project/form2/models.py
from django.db import models

# Create your models here.

third_project/index/models.py
from django.db import models

# Create your models here.

third_project/special/models.py
from django.db import models

# Create your models here.

third_project/user_login/models.py
from django.db import models

# Create your models here.

third_project/form/forms.py
from django import forms
from django.core import validators

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again:")
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email=all_clean_data['email']
        vmail=all_clean_data['verify_email']

        if email!=vmail:
            raise forms.ValidationError("Make sure you're emails match")

third_project/form2/forms.py
from django import forms
from contact.models import Contact


class FormName(forms.ModelForm):
    class Meta:
        model=Contact
        fields= '__all__'

third_project/contact/views.py
from django.shortcuts import render
from contact.models import Contact

# Create your views here.
def contact(request):
    contactlist = Contact.objects.order_by('last_name')
    contact_dict={'contact_records':contactlist}
    return render(request,'contact/contact.html',context= contact_dict)

third_project/form/views.py
from django.shortcuts import render
from . import forms
# Create your views here.
def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form=forms.FormName(request.POST)

    if form.is_valid():
        print("Validation Succes")
        print("Name "+form.cleaned_data['name'])
        print("Email "+form.cleaned_data['email'])
        print("Text "+form.cleaned_data['text'])
    return render(request,'form/form.html',{'form':form})

third_project/form2/views.py
from django.shortcuts import render
from . import forms
from index.views import index

# Create your views here.
def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form=forms.FormName(request.POST)

    if form.is_valid():
        new_contact = form.save(commit=True)
        return index(request)

    return render(request,'form2/form2.html',{'form':form})

third_project/index/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    my_dict ={'insert_me': 'This is a Lebron James fanpage'}
    return render(request,'index/index.html',context=my_dict)

third_project/special/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

third_project/user_login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

# Create your views here.
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account is not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password{}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'user_login/user_login.html',{})

third_project/templates/base/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="{% static 'css/style2.css'%}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li> <a class="navbar-link" href="{% url 'index'%}">Home </a></li>
        <li> <a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
        <li> <a class="navbar-link" href="{% url 'form:form'%}">Contact Form1</a></li>
        <li> <a class="navbar-link" href="{% url 'form2:form2'%}">Contact Form2</a></li>
        <li> <a class="navbar-link" href="{% url 'contact:contact'%}">Contact Info</a></li>
        <li> <a class="navbar-link" href="{% url 'registration:registration'%}">Registration</a></li>
        {% if user.is_authenticated %}
        <li> <a class="navbar-link" href="{% url 'user_logout:user_logout'%}">Logout</a></li>
        {%else%}
        <li> <a class="navbar-link" href="{% url 'user_login:user_login'%}">Login</a></li>
        {%endif%}
      </ul>
    </div>
  </nav>
  <div class="container">
    {%block body_block %}


    {% endblock %}
  </div>

</body>

</html>

third_project/templates/index/index.html
<!DOCTYPE html>
{% extends "base/base.html" %}
{%load static%}
{%load my_template_tags%}
{% block body_block%}
<h1>Lebron James</h1>
<p>{{insert_me|cuts:'James'}}</p>
<img src="{% static 'images/lebronjames.jpg'%}" alt="">
{% endblock %}